packages:
  - packages/*

catalogs:
  build:
    tsup: ^8.5.1
    tsx: ^4.21.0
    turbo: ^2.6.3
  dev:
    nano-staged: ^0.9.0
    simple-git-hooks: ^2.13.1
  lint:
    '@eslint/eslintrc': ^3.3.3
    '@eslint/js': ^9.39.1
    '@typescript-eslint/eslint-plugin': ^8.49.0
    '@typescript-eslint/parser': ^8.49.0
    dprint: ^0.50.2
    eslint: ^9.39.1
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-turbo: ^2.6.3
    eslint-plugin-unused-imports: ^4.3.0
  prod:
    zod: ^4.1.13
  types:
    '@fengkx/tsconfig': ^2.0.0
    '@types/node': ^25.0.0
    globals: ^16.5.0
    type-fest: ^5.3.1
    typescript: ^5.9.3

onlyBuiltDependencies:
  - '@fengkx/tree-sitter-beancount'
  - '@swc/core'
  - '@vscode/vsce-sign'
  - dprint
  - esbuild
  - simple-git-hooks
  - tree-sitter-cli
  - keytar
