packages:
  - packages/*

catalogs:
  build:
    tsup: ^8.5.0
    turbo: ^2.5.4
    tsx: ^4.20.3
  lint:
    dprint: ^0.50.0
    eslint: ^9.30.0
    '@eslint/eslintrc': ^3.3.1
    '@eslint/js': ^9.30.0
    '@typescript-eslint/eslint-plugin': ^8.35.0
    '@typescript-eslint/parser': ^8.35.0
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-turbo: ^2.5.4
    eslint-plugin-unused-imports: ^4.1.4
  types:
    '@types/node': ^24.0.7
    '@fengkx/tsconfig': ^2.0.0
    typescript: ^5.8.3
    type-fest: ^4.41.0
    globals: ^16.2.0
  dev:
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.13.0
  prod:
    zod: ^3.25.67

onlyBuiltDependencies:
  - '@fengkx/tree-sitter-beancount'
  - '@swc/core'
  - '@vscode/vsce-sign'
  - dprint
  - esbuild
  - simple-git-hooks
  - tree-sitter-cli
  - keytar
