packages:
  - packages/*

catalogs:
  build:
    tsup: ^8.5.0
    tsx: ^4.20.6
    turbo: ^2.5.8
  dev:
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.13.1
  lint:
    '@eslint/eslintrc': ^3.3.1
    '@eslint/js': ^9.37.0
    '@typescript-eslint/eslint-plugin': ^8.46.1
    '@typescript-eslint/parser': ^8.46.1
    dprint: ^0.50.2
    eslint: ^9.37.0
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-turbo: ^2.5.8
    eslint-plugin-unused-imports: ^4.3.0
  prod:
    zod: ^4.1.12
  types:
    '@fengkx/tsconfig': ^2.0.0
    '@types/node': ^24.8.1
    globals: ^16.4.0
    type-fest: ^5.1.0
    typescript: ^5.9.3

onlyBuiltDependencies:
  - '@fengkx/tree-sitter-beancount'
  - '@swc/core'
  - '@vscode/vsce-sign'
  - dprint
  - esbuild
  - simple-git-hooks
  - tree-sitter-cli
  - keytar
