packages:
  - packages/*

catalogs:
  build:
    tsup: ^8.5.0
    tsx: ^4.20.4
    turbo: ^2.5.6
  dev:
    nano-staged: ^0.8.0
    simple-git-hooks: ^2.13.1
  lint:
    '@eslint/eslintrc': ^3.3.1
    '@eslint/js': ^9.36.0
    '@typescript-eslint/eslint-plugin': ^8.44.1
    '@typescript-eslint/parser': ^8.44.1
    dprint: ^0.50.2
    eslint: ^9.36.0
    eslint-import-resolver-typescript: ^4.4.4
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-turbo: ^2.5.8
    eslint-plugin-unused-imports: ^4.2.0
  prod:
    zod: ^4.1.11
  types:
    '@fengkx/tsconfig': ^2.0.0
    '@types/node': ^24.5.2
    globals: ^16.4.0
    type-fest: ^5.0.1
    typescript: ^5.9.2

onlyBuiltDependencies:
  - '@fengkx/tree-sitter-beancount'
  - '@swc/core'
  - '@vscode/vsce-sign'
  - dprint
  - esbuild
  - simple-git-hooks
  - tree-sitter-cli
  - keytar
