name: Publish Extension

# Control concurrency for this workflow to prevent multiple versions being published simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering
    inputs:
      publish_to_marketplace:
        description: 'Publish to Extension Marketplace'
        required: true
        default: 'false'
        type: boolean
      prerelease:
        description: 'Publish as prerelease version'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write  # Changed from read to write to allow commits
  packages: read
  
jobs:
  build-and-publish:
    name: Build and Publish Extension
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: production  # Use environment for protection
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true
  
      - name: Build packages
        run: pnpm build

      - name: Generate CHANGELOG.md
        run: node scripts/generate-changelog.js

      - name: Package Extension
        run: pnpm --filter beancount-lsp-client vsix ${{ github.event.inputs.prerelease == 'true' && '--pre-release' || '' }}
      
      - name: Find VSIX file
        id: find-vsix
        run: |
          VSIX_FILE=$(find packages/lsp-client -name "beancount-lsp-client-*.vsix" | head -n 1)
          echo "Found VSIX file: $VSIX_FILE"
          echo "vsix_file=$VSIX_FILE" >> $GITHUB_OUTPUT
        
      - name: Upload VSIX as artifact (for reference)
        uses: actions/upload-artifact@v4
        with:
          name: beancount-lsp-extension
          path: packages/lsp-client/beancount-lsp-client-*.vsix
          if-no-files-found: error
          retention-days: 7

      - name: Publish to Visual Studio Marketplace
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_marketplace == 'true')
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          extensionFile: ${{ steps.find-vsix.outputs.vsix_file }}
          registryUrl: https://marketplace.visualstudio.com 
          preRelease: ${{ github.event.inputs.prerelease == 'true' }}
        
      - name: Publish to Open VSX Registry
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_marketplace == 'true')
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSIX_PAT }}
          extensionFile: ${{ steps.find-vsix.outputs.vsix_file }}
          preRelease: ${{ github.event.inputs.prerelease == 'true' }}
      
      # Commit CHANGELOG.md after successful publish
      - name: Commit CHANGELOG.md
        if: success() && github.event.inputs.publish_to_marketplace == 'true'
        run: |
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Get version from package.json
          VERSION=$(node -p "require('./packages/lsp-client/package.json').version")
          
          # Check if there are changes to the CHANGELOG
          if git diff --quiet packages/lsp-client/CHANGELOG.md; then
            echo "No changes to CHANGELOG.md, skipping commit"
          else
            echo "Changes detected in CHANGELOG.md, committing..."
            git add packages/lsp-client/CHANGELOG.md
            git commit -m "docs: update CHANGELOG.md for v${VERSION}"
            git push
          fi