name: Publish Extension

# Control concurrency for this workflow to prevent multiple versions being published simultaneously
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering
    inputs:
      publish_to_marketplace:
        description: 'Publish to VS Code Marketplace'
        required: true
        default: 'false'
        type: boolean

permissions:
  contents: read
  packages: read
  
jobs:
  build-and-publish:
    name: Build and Publish Extension
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: production  # Use environment for protection
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true
  
      - name: Build packages
        run: pnpm build

      - name: Package Extension
        run: pnpm --filter beancount-lsp-client vsix
      
      - name: Find VSIX file
        id: find-vsix
        run: |
          VSIX_FILE=$(find packages/lsp-client -name "beancount-lsp-client-*.vsix" | head -n 1)
          echo "Found VSIX file: $VSIX_FILE"
          echo "vsix_file=$VSIX_FILE" >> $GITHUB_OUTPUT
        
      - name: Upload VSIX as artifact (for reference)
        uses: actions/upload-artifact@v4
        with:
          name: beancount-lsp-extension
          path: packages/lsp-client/beancount-lsp-client-*.vsix
          if-no-files-found: error
          retention-days: 7

      - name: Publish to Visual Studio Marketplace
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_to_marketplace == 'true')
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          extensionFile: ${{ steps.find-vsix.outputs.vsix_file }}
          registryUrl: https://marketplace.visualstudio.com 